repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true