version: '3.8'

services:
#  bot:
#    build:
#      dockerfile: dockerfile
#    env_file:
#      - .env

  #  migration:
  #    build:
  #      dockerfile: dockerfile
  #    command: bash -c "aerich upgrade"
  #    volumes:
  #      - .:/usr/src
  #    depends_on:
  #      - db

#  db:
#    image: postgres:14
#    environment:
#      - POSTGRES_DB=devdb
#      - POSTGRES_USER=devdb
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-dev:/var/lib/postgresql/data

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=grog
      - MYSQL_ROOT_PASSWORD=grog
      - MYSQL_USER=grog
      - MYSQL_PASSWORD=grog
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db: { }
